[dependencies]
ferrisgram = "0.1.9"
tokio = { version = "1.37.0", features = ["full"] }
time = "0.3.34"
reqwest = "0.12.3"

[profile.release]
lto = true
opt-level = "z"
incremental = true
codegen-units = 1
target-cpu = "native"
link-arg = "-s"

[package]
name = "rustrobot"
version = "0.0.1"
include = ["/src"]
edition = "2021"
