[dependencies]
ferrisgram = "0.1.9"
tokio = { version = "1.37.0", features = ["full"] }
time = "0.3.34"
reqwest = "0.12.3"

[package]
name = "rustrobot"
version = "0.0.1"
include = ["/src"]
edition = "2021"
