[dependencies]
ferrisgram = "0.2.1"
async-std = "1.13.0"
tokio = { version = "1.40.0", features = ["full"] }

[profile.release]
lto = true
opt-level = "z"
incremental = true

[package]
name = "rustrobot"
version = "0.0.1"
include = ["/src"]
edition = "2021"
